let Arr = {
    'а': require('./images/a.jpeg'), 
    'ә': require('./images/ak.jpeg'),
    'б': require('./images/b.jpeg'),
    'в': require('./images/v.jpeg'),
    'г': require('./images/g.jpeg'),
    'ғ': require('./images/gk.jpeg'),
    'д': require('./images/d.jpeg'),
    'е': require('./images/e.jpeg'),
    'ё': require('./images/yo.jpeg'),
    'ж': require('./images/zh.jpeg'),
    'з': require('./images/z.jpeg'),
    'и': require('./images/i.jpeg'),
    'й': require('./images/y.jpeg'),
    'к': require('./images/k.jpeg'),
    'қ': require('./images/kk.jpeg'),
    'л': require('./images/l.jpeg'),
    'м': require('./images/m.jpeg'),
    'н': require('./images/n.jpeg'),
    'ң': require('./images/nk.jpeg'),
    'о': require('./images/o.jpeg'),
    'ө': require('./images/ok.jpeg'),
    'п': require('./images/p.jpeg'),
    'р': require('./images/r.jpeg'),
    'с': require('./images/c.jpeg'),
    'т': require('./images/t.jpeg'),
    'у': require('./images/u.jpeg'),
    'ұ': require('./images/kuk.jpeg'),
    'ү': require('./images/uk.jpeg'),
    'ф': require('./images/f.jpeg'),
    'х': require('./images/h.jpeg'),
    'һ': require('./images/hk.jpeg'),
    'ц': require('./images/tc.jpeg'),
    'ч': require('./images/ch.jpeg'),
    'ш': require('./images/sh.jpeg'),
    'щ': require('./images/shch.jpeg'),
    'ъ': require('./images/".jpeg'),
    'ы': require('./images/yi.jpeg'),
    'і': require('./images/ik.jpeg'),
    // 'ь': require('./images/..jpeg'),
    'э': require('./images/ea.jpeg'),
    'ю': require('./images/iu.jpeg'),
    'я': require('./images/ia.jpeg')
}

export default Arr;
